### ISSUE TITLE
Disable warning 70 or generating an interface file

### ISSUE THREAD

**Issue by fangyi-zhou** [issuu/ocaml-protoc-plugin#35]
Hi, I'm wondering whether it would be appropriate to add a flag to emit a suppression of warning 70 (missing mli file), or a flag to generate an interface file. In either case, I'm happy to submit a pull request.

**Comment by andersfugmann** [comment]
Emitting a .mli file is a lot of work, and I hardly see any value in generting `.mli` files when the `.mli` file exposes the same signature as inferred signature of the `.ml` file.

But I don't see any harm in disabling warning 70 in the auto-generated files.

**Comment by fangyi-zhou** [comment]
It seems that `[@@@warning "-70"]` does not suppress the warning, I guess the supression needs to be done manually in compilation flags. Please feel free to close this issue.

See https://github.com/ocaml/RFCs/pull/26 https://github.com/ocaml/ocaml/pull/10319

**Comment by andersfugmann** [comment]
I assume that you have enabled warning 70 on your project which is why you see this error. 
One solution for you could be to place all protoc auto generated files in a separate library (if you are using dune to control the build process), and disable warning 70 when compiling the library). 

Closing for now.
