### ISSUE TITLE
Google's well known types

### ISSUE THREAD

**Issue by wokalski** [issuu/ocaml-protoc-plugin#9]
I use some of [google's well known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) in my project. Currently, if I use them in my schema, the code is generated properly but the encoders and decoders are not defined for the well known types (i.e. `Struct.Google.Protobuf.Struct.t` causes `Unbound module Struct.Google`). It's easy to work around by simply copying the relevant proto files so it's not a critical issue. I'm just wondering if supporting those is within the scope of this project.

**Comment by andersfugmann** [comment]
I have been considering this - and I think I've come up with a solution (the challenge is that often you would like to use ppx-deriving (eq, ord, show etc.), and since I've made an effort to slim the amount of dependencies on the project, I would need to add these derivers by hand (or run through the ppx and store the output. 

As you say, the easy workaround is to copy the protofiles - actually you do not need to copy them as you can just reference the original proto file using an absolute path.

**Comment by andersfugmann** [comment]
Its on master now. I'll make release 2.0.0 soon.

**Comment by wokalski** [comment]
Awesome. I made some investigation into how to bring this to bucklescript-world and it's possible using generators - similar to dune rules. Unfortunately I'm not sure what's the best way to indicate the path to proto files. Maybe some environment variable? I'm not sure if relying on `/usr/include/google/protobuf` is a good solution.

**Comment by andersfugmann** [comment]
Take a look at the https://github.com/issuu/ocaml-protoc-plugin/blob/master/src/google_types/dune
At least it works on both linux and osx.
